Add calendar functionality
CamJak/Boss-Integrated-Scheduler pull request #25
Opened 2023-05-02 03:17 UTC by CamJak

Implemented a lot of functionality to the calendar page as well as other project-wide changes. These changes combine to form the first working prototype of the calendar as all required functionality is implemented. Please see commits for details on specific additions.

2023-05-03 14:39 UTC, CamJak commented on api/src/routers/getSectionByCallNumber.ts
Do we want to move this into sections.ts?

2023-05-03 16:38 UTC, JingusJohn requested changes

2023-05-03 16:38 UTC, jackjohn7 commented on App/src/lib/stores/quarter.ts
> +let firstRun = true;
This variable doesn't look to actually do anything. Going to remove it since things seem to work without it.

2023-05-03 16:38 UTC, jackjohn7 commented on WebScraper/main.py
> +    quarter = "Summer 2023"
Should parameterize this in some way

2023-05-03 16:38 UTC, jackjohn7 commented on api/src/routers/getSectionByCallNumber.ts
> +export const getSectionByCallNumberRouter = t.router({
I'm gonna go ahead and add this to the subjects router. It doesn't need its own router.

2023-05-03 16:38 UTC, jackjohn7 commented on api/src/routers/quarters.ts
> +      if (seasonValue(q.season) > seasonValue(latestQuarter.season)) latestQuarter = q;
I need to scrape Summer 2023 to make extra sure these sorting functions are working. It's working with Spring and Fall, but adding Summer to the mix given that it would have been scraped after will make it a pretty decent test.

2023-05-05 01:46 UTC, JingusJohn approved these changes

2023-05-05 01:46 UTC, merged